default:
  dynaconf_merge: true
  kuadrantctl: "kuadrantctl"
  tools:
    project: "tools"
  cfssl: "cfssl"
  keycloak:
    username: "admin"
    test_user:
      username: "testUser"
      password: "testPassword"
  httpbin:
    image: "quay.io/rhn_support_azgabur/httpbin:latest"
  llm_sim:
    image: "ghcr.io/llm-d/llm-d-inference-sim:v0.1.1"
    model: "kuadrant/model"
  mockserver:
    image: "quay.io/rhn_support_azgabur/mockserver:latest"
  service_protection:
    system_project: "kuadrant-system"
    project: "kuadrant"
    project2: "kuadrant2"
    envoy:
      image: "quay.io/trepel/envoy:v1.35-latest"
    gateway:
       project: "istio-system"
       name: "istio-ingressgateway"
    authorino:
      deploy: true
      log_level: "debug"
  control_plane:
    cluster: {}
    slow_loadbalancers: false
    provider_secret: "aws-credentials"
    issuer:
      name: "kuadrant-qe-issuer"
      kind: "ClusterIssuer"
  letsencrypt:
    issuer:
      name: "letsencrypt-staging-issuer"
      kind: "Issuer"
